Home page
Zyabrik10/team-project-cocktails-website pull request #9
Opened 2023-10-28 18:02 UTC by irysik123

logic for home page (/home), rendering cards according to the screen (desk, tab, mob), basic styles

2023-10-28 19:31 UTC, Zyabrik10 requested changes

2023-10-28 19:31 UTC, Zyabrik10 commented on src/pages/home/components/sec-ordinary-drink/OrdinaryDrink.jsx
> +        <Link>See more</Link>
теж саме

2023-10-28 19:31 UTC, Zyabrik10 commented on src/pages/home/components/sec-hero/Hero.jsx
> +        // to="/add"
link нікуди не веде, це може призвести до warning, а гыт хаб на це дуже свариться, якщо пока немає сторінки, то краще просто зроби як `<p></p>`

2023-10-28 19:31 UTC, Zyabrik10 commented on src/pages/home/components/DrinkContainer.jsx
> +      <Link>Other Drinks</Link>
проблеми з Link я описав у низу

2023-10-28 19:32 UTC, Zyabrik10 commented
ще є конфлітки, виправи будь-ласка

2023-10-29 03:54 UTC, irysik123 commented
виправила всюди Лінк на Р

2023-10-29 09:27 UTC, Zyabrik10 approved these changes

2023-10-29 09:27 UTC, merged